---
sudo: false
language: perl
perl:
  - "5.30"
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
install:
  - cpanm --quiet --notest --installdeps .
script:
  - prove -l $(test-files)
